# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3665886384ce9c32d9acf6c4c26aa1e44f3a462d453d4648b0075ffac5d3842010ec623388c44972c1227dda4ab0c4e5a7c4591fee9a0d99e21faadaf5233a12

test:
  secret_key_base: e0852dfe6afc9ac688913a00e6b558c6b5b9d6e0bdd2675239f75b09c3584b6ff16668b9bd9f01325f6a577dde0f3529a6bab40aa31d993f76b51b08b48930ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
